### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#12]
Should mainly cover spec documentation, but also any code in this repo

**Comment by pgleeson** [comment]
@davidt0x Not sure GNU LGPLv3 is most appropriate for the package, as Ted was keen on something more commercially acceptable like BSD or MIT. Will check.

**Comment by davidt0x** [comment]
ok, i just went with LGPLv3 because it was already in the classifiers within setup.py. I will keep it for now and merge the PR. We can swap it out for later. For what its worth, I agree with Ted, I think either BSD or Apache would be a better choice.

**Comment by pgleeson** [comment]
From @jdcpni: " We’ve been using Apache.  Any reason not to?"
