### ISSUE TITLE
Restricting data type of inputs to allowed data type

### ISSUE THREAD

**Issue by mraunak** [ModECI/MDF#124]
Currently, MDF permits input to core elements in a data type different from the allowed data type. e.g. parameters and conditions are the attributes of the 'Graph' object and allowed data types to these attributes are 'parameters' ---> dict and 'conditions'---> dict, however, while testing 'parameters' and 'conditions' accept inputs in 'string', integer formats as well.

To resolve this, there should be a check applied to restrict the data type of the inputs provided to the allowed data type

**Comment by pgleeson** [comment]
This is fixed in development now
