### ISSUE TITLE
Release v0.3.2

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#183]
@davidt0x can you do a release of this on PYPI?

https://github.com/ModECI/MDF/releases/tag/v0.3.2

**Comment by davidt0x** [comment]
@pgleeson, the release to PyPI is handled automatically when a release is tagged, you can see it here in the "Distribution Build" job from the actions log:

https://github.com/ModECI/MDF/runs/4406484410?check_suite_focus=true

**Comment by pgleeson** [comment]
@davidt0x Thanks. I suspected that was the case, but the release hadn't show up on pypi when I checked. I'll be more patient next time...
