### ISSUE TITLE
MDF to PyTorch export

### ISSUE THREAD

**Issue by mraunak** [ModECI/MDF#185]
The code to export MDF models to PyTorch models is available on the mdf_pytorch branch

Next Task: Implement Multiple Functions on a Node in equivalent PyTorch model and export it to ONNX for evaluation

**Comment by mraunak** [comment]
Implemented Multiple Functions on a Node in equivalent PyTorch model and export it to ONNX for evaluation.

Next Task: Map ONNX operator to PyTorch Functions to facilitate the conversion of an MDF-based PyTorch model to convert back to PyTorch model. It is even useful for any other model which uses onnx operator and needs to be converted to PyTorch

**Comment by pgleeson** [comment]
MDF to and from PyTorch well supported now: https://github.com/ModECI/MDF/blob/main/examples/PyTorch/README.md.
Specific additions should be opened as issues
