### ISSUE TITLE
Add text box in contact form: Type your message here

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#202]
Currently nothing there for someone to ask us anything: http://modeci.org/#contactPage

Source: https://github.com/ModECI/Website/blob/main/_includes/contact.html

**Comment by IdealisticINTJ** [comment]
Hi @pgleeson,
I'd like to work on this issue, as an Outreachy applicant. Please assign it to me.

**Comment by martwebber** [comment]
Hello @pgleeson, I am an Outreachy applicant and I would love to contribute to this issue.

**Comment by pochernina** [comment]
Hi @pgleeson, I would also like to join this task as an Outreachy appliciant.

**Comment by pgleeson** [comment]
This issue has been solved with this pull request: https://github.com/ModECI/Website/pull/39. It was a relatively small one. I'll add some more details on tasks for Outreachy applicants.
