### ISSUE TITLE
Add Installation/Quick Start pages to documentation 

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#208]
This is an omission in the docs at https://mdf.readthedocs.io

Doesn't need to be much more complicated than pip install... and running soem examples in examples/MDF, and then pointing to the notebook at https://github.com/ModECI/MDF/blob/main/examples/SimpleExample.ipynb

**Comment by martwebber** [comment]
Hello @pgleeson, I am an Outreachy applicant and I would love to contribute to this issue.

**Comment by Mercytopsy** [comment]
Hello @pgleeson, I will like to contribute to this issue

**Comment by pgleeson** [comment]
Done.
