### ISSUE TITLE
Contributing Guideline to make Contributions

### ISSUE THREAD

**Issue by shivani6320** [ModECI/MDF#221]
Hello @pgleeson @sanjayankur31 , I have a suggestion  you'd like to consider -- I believe we should have a **Contributing Guide** to help all the contributors which also makes it easier for mentors to keep track of all contributions by applicants.
- It will help all the new contributors to make contributions to this repo, help get started with the project as well as makes the contributing process hassle-free for all.
- The guide will contain information on **Project Contribution,MDF Installation Guide,Steps to Contribute & Resources** for begineers.

**Comment by FatimaArshad-DS** [comment]
Please check #225

**Comment by pgleeson** [comment]
Thanks for this @shivani6320. This will be useful as a general guide to new users/developers of MDF independent of Outreachy. I'll review.
