### ISSUE TITLE
Add link to GitHub discussions on main website

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#228]
At the section Get In Contact here: http://modeci.org/, there should be a sentence to say that disussions around the standard and software are taking place on GitHub Discussions. Source for website: https://github.com/ModECI/Website

**Comment by somyagr** [comment]
I've opened a pull request there, please check.

**Comment by 29riyasaxena** [comment]
> At the section Get In Contact here: http://modeci.org/, there should be a sentence to say that disussions around the standard and software are taking place on GitHub Discussions. Source for website: https://github.com/ModECI/Website

Hi! I have opened a pull request on the website github, please look after it.

**Comment by pgleeson** [comment]
Done.
