### ISSUE TITLE
PyTorch -> MDF pipeline

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#23]
@davidt0x @patrickstock Can you add details on status?

**Comment by davidt0x** [comment]
Rough version of the torchscript to MDF translator in `modeci_mdf.export.torchscript`. Still a work in progress.

- [x] Parsing and translation of TorchScript IR graph to MDF
- [x] Removal of constant TorchScript nodes (they become parameters in MDF)   
- [ ] No execution, the MDF is full of TorchScript operators, working on this now.
- [ ] Consolidation (maybe removal) of some primitive operators that TorchScript uses a lot (prim::ListConstruct, prim::TupleConstruct). I think we can flesh out the MDF spec a bit more to allow tuples and lists of parameters and input ports to be passed as arguments to functions. I think this would allow us to remove a lot these.
- [ ] Control flow is still not handled really. Loop and If operators are translated but the blocks (subgraphs that contain their computations) are not being recursively generated in MDF. I had something working but there is a bug. Need to think about this a bit in light of the conditions stuff.
