### ISSUE TITLE
Remove version caps on package dependencies.

### ISSUE THREAD

**Issue by davidt0x** [ModECI/MDF#230]
We are doing this, there are a lot of reasons that this is not a good idea for packages that are meant to be libraries like MDF. [Here](https://iscinumpy.dev/post/bound-version-constraints/) is a very long :) discussion about it by one of my fellow RSEs here at Princeton. Here is a the [TLDR;](https://iscinumpy.dev/post/bound-version-constraints/#tldr). This is already causing issues between PsyNeuLink (where we also version cap) and MDF. I tried to install a fresh install of psyneulink the other day on a clean environment and the pip solver got stuck backtracking. Additionally, we have PyTorch pinned to 1.8 now and @mraunak last merged in PR has tests that fail on PyTorch 1.9 on my end. These are not being caught in CI. This is especially true in the PyTorch case because we are using several internal APIs that are subject to change.  Anyway, I vote to remove the version caps and to deal with breaking changes and deprecations from libraries as they come. We can always provide an optional locked set of dependencies for a reproduceable environment down the line.

**Comment by ALopez3531** [comment]
Hello, my name is Alonso Lopez and I am an Outreachy applicant. I am interested in taking on this task.

**Comment by pgleeson** [comment]
Please see https://github.com/ModECI/MDF/discussions/225#discussioncomment-2509898 for discussions around the context for this. It will basically involve forking the project and changing the version constraints in https://github.com/ModECI/MDF/blob/development/setup.cfg and making sure the GitHub actions are still passing. Make sure to do this from the development branch.

**Comment by ALopez3531** [comment]
Hello, 

I have been working on changing the constraints and was hoping I could receive some advice for the issue I have come across. I changed the constraints for the pytorch dependency within setup.cfg and ran the tests, which the new program did not pass. I then modified the arguments in the _model_to_graph() function contained within the importer.py file, and the program passed two tests. However now I received the following error:

self = <onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x7f47082f6670>, providers = [], provider_options = []
    def _create_inference_session(self, providers, provider_options):
        available_providers = C.get_available_providers()
        # validate providers and provider_options before other initialization
        providers, provider_options = check_and_normalize_provider_args(providers,
                                                                        provider_options,
                                                                        available_providers)
        # Tensorrt can fall back to CUDA. All others fall back to CPU.
        if 'TensorrtExecutionProvider' in available_providers:
            self._fallback_providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
        else:
            self._fallback_providers = ['CPUExecutionProvider']
        session_options = self._sess_options if self._sess_options else C.get_default_session_options()
        if self._model_path:
            sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
        else:
>           sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
E           onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(int64)' of input parameter (input_sequence) of operator (ConcatFromSequence) in node (Co_ConcatFromSequence) is invalid.
../../../.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:309: InvalidGraph

**Comment by pgleeson** [comment]
@ALopez3531 Are you making these changes in a fork of the repository? The simplest way to share your changes and for us to see the precise errors (for multiple python versions) is to commit your changes to a fork, and enable tests to be run at the Actions tab.

**Comment by ALopez3531** [comment]
@pgleeson Alright my changes should be available now.

**Comment by pgleeson** [comment]
Thanks @ALopez3531, but you'll have to be a bit more specific about what you've done, why you think it should work and which tests are failing.

**Comment by ALopez3531** [comment]
Hello @pgleeson, I made some comments under the edits that I made, I was hoping you could check them out.

**Comment by pgleeson** [comment]
Thanks again @ALopez3531. I'm afraid it wasn't possible to look at your edits in detail before the Outreachy application deadline.

Can you point here to the specific edits/comments you made (simplest is to mention @pgleeson in the comment)?

**Comment by davidt0x** [comment]
Hey @parikshit14, 

What is the error you are getting? These are the ones I get on my end, the same as in CI:

[](https://github.com/ModECI/MDF/runs/6756800133?check_suite_focus=true)

This looks like an issue with sympy trying to evaluate the strings we use to encode onnx functions. I am not sure why this started happening. Perhaps I need to pin the sympy version further back (I left that pin in and removed all others) or maybe it is related to an issue with the new pytorch. I didn't have more time to dig into this.

**Comment by parikshit14** [comment]
![Screenshot from 2022-06-10 12-43-18](https://user-images.githubusercontent.com/54709254/173011195-865a8264-aa7e-4c94-9685-725367d0bb38.png)

**Comment by davidt0x** [comment]
Hey @parikshit14, which directory are you running pytest from?

**Comment by davidt0x** [comment]
Ok, you are probably running the pytest command `pytest`. This is different in one subtle way from running `python -m pytest`, it doesn't prepend the current working directory to sys.path. See here [here](https://docs.pytest.org/en/6.2.x/pythonpath.html#invoking-pytest-versus-python-m-pytest). For now, I would use python -m pytest if running pytest from command line. This is probably what PyCharm's pytest runner does as well so I never caught this issue. That being said, I am not sure I like this practice in these tests of importing from examples. We already have a test that runs all examples. @mraunak, I believe you wrote these tests. I am trying to understand them. Are these examples automatically generated pytorch code from MDF? If so, where is the code that generates them?

**Comment by davidt0x** [comment]
Also, even if you run with `python -m pytest`, one of the Arrays test will fail because of a missing module attribute `res`. This is because I commented out running the example in Arrays_pytorch.py because it was failing on newer PyTorch. This is because torch.jit.script now seems to optimize out unused inputs to models leaving the resulting ONNX graph with no inputs. Not sure if this bug has been fixed in PyTorch yet or if they even consider it a feature. I think it would be best to modify the examples so that they actually use their inputs in the computation. This would make the example better as well as fix the problem. Any chance you could do this @mraunak.

**Comment by mraunak** [comment]
@davidt0x the code to generate examples - https://github.com/ModECI/MDF/blob/development/examples/PyTorch/MDF_PyTorch/MDF_to_PyTorch.py

The current implementation of MDF to PyTorch generates PyTorch model as well as onnx files, so if we call directly exporter.py while testing, it will generate PyTorch and onnx models in the test module, to eliminate having the same file in the multiple folders, it was collectively stored in the examples, we can discuss a better way to import the PyTorch/ONNX/TensorFlow models generated within MDF.

**Comment by davidt0x** [comment]
I think my new pushes to [remove_version_caps](https://github.com/ModECI/MDF/tree/remove_version_caps) should fix all the version caps except the sympy issue. @parikshit14 do you want to take a look at fixing the sympy version cap. Ultimately, I think it would be nice to drop this dependency actually. I think we can get away with using `ast.parse` from the standard library to get the variables from python expression. We can also then filter out any builtins that get evaluated and rename them or something.

**Comment by pgleeson** [comment]
This is fixed in the main branch, apart from sympy<=1.8. Opening separate issue.
