### ISSUE TITLE
Test why links/anchors not translating properly in sphinx

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#262]
e.g. for #node
These links work: https://github.com/ModECI/MDF/blob/main/docs/sphinx/source/api/Specification.rst#node
These don't: https://mdf.readthedocs.io/en/latest/api/Specification.html#node

To regenerate the documentation (with latest development of modelspec and MDF):

- run https://github.com/ModECI/MDF/blob/main/docs/generate.py 
- go to docs/sphinx
- type `make html`

**Comment by parikshit14** [comment]
Hi @pgleeson I am having difficulty running ``` make html``` 
It gives me the following error 

    from sphinx.ext.autodoc import ClassLevelDocumenter, InstanceAttributeDocumenter
    ImportError: cannot import name 'InstanceAttributeDocumenter' from 'sphinx.ext.autodoc'

Is this a version related issue
**sphinx version = 5.0.1**

**Comment by pgleeson** [comment]
@parikshit14 I had Sphinx-3.5.4, and updated it to the latest and got the error you found also.

Sphinx 3 is recommended here (and there's capping on other packages):
https://github.com/ModECI/MDF/blob/19d42125fdcb2b32496a2bfa85c1dcfdf126cd0d/setup.py#L15

Any reason for using this version @davidt0x @mraunak?

**Comment by pgleeson** [comment]
Links in live generated docs are working fine now, e.g. https://mdf.readthedocs.io/en/latest/api/Specification.html#node
