### ISSUE TITLE
Add Pytorch_to_MDF example

### ISSUE THREAD

**Issue by parikshit14** [ModECI/MDF#276]
Adding a basic example like the ABCD_pytorch to the examples/pytorch folder.

- must convert to MDF format
- add graphical representation to the readme

@pgleeson do add any other pointers if I missed any.

**Comment by mraunak** [comment]
I had added a few examples which convert PyTorch to MDF https://github.com/ModECI/MDF/tree/mdf_to_onnx/examples/PyTorch/PyTorch_MDF

**Comment by parikshit14** [comment]
@pgleeson as I can see all these examples by @mraunak had a `example_outputs` https://github.com/ModECI/MDF/blob/mdf_to_onnx/examples/PyTorch/PyTorch_MDF/convolution.py#L65 parameter to the `pytorch_to_mdf` function, were these supported in the older versions of this function, as I am having trouble running them. Also there seems to be no assertion for verifying the two outputs are they needed or are we just trying to convert to mdf and export to json formats

**Comment by mraunak** [comment]
Test cases are available here: 
https://github.com/ModECI/MDF/blob/mdf_to_onnx/tests/interfaces/pytorch/test_import.py

**Comment by parikshit14** [comment]
@mraunak I am having difficulty running, some internal changes in `execution_engine.py` and `mdf.py` are the probable ones, I tried setting an env according to your branch for the dependencies and src from the current dev branch so most probably the src folder changes are the ones creating problem.
(While the examples runs fine in your branch.)

line causing the error:
`eg.evaluate(initializer=params_dict)` https://github.com/ModECI/MDF/blob/a4ed0f3b03e8bc52e521a9d310861c5897bcd3c7/tests/interfaces/pytorch/test_import.py#L115

also current version doesn't support https://github.com/ModECI/MDF/blob/a4ed0f3b03e8bc52e521a9d310861c5897bcd3c7/tests/interfaces/pytorch/test_import.py#L105
so I tried removing this.

however, I think I will need to find the correct versions of the mdf code(from src) using the history. What do you think?

**Comment by mraunak** [comment]
Try running pytorch/test_import.py on the mdf_to_onnx branch on your machine without making any changes if it works then start incorporating the latest changes and debug if it gives an error. I had made some changes in the execution engine and pytorch/importer.py

**Comment by parikshit14** [comment]
@mraunak got it thanks!!!

**Comment by pgleeson** [comment]
Done at https://github.com/ModECI/MDF/blob/main/examples/PyTorch/README.md
