### ISSUE TITLE
graph_scheduler 1.1.0 & 1.1.1 seem to lead to an earlier version of psyneulink being installed.

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#287]
These commits only use graph_scheduler >1.0.0:

**graph_scheduler = 1.1.1**
https://pipelines.actions.githubusercontent.com/serviceHosts/205fed67-e757-4d4c-8ffc-a6fc67c1479e/_apis/pipelines/1/runs/1230/signedlogcontent/6?urlExpires=2022-07-08T11%3A47%3A27.4404148Z&urlSigningMethod=HMACV1&urlSignature=tMA5sm82%2FLk9aqqca1DKn%2BgvNAGdDG6D6x7W7rCChlw%3D

**graph_scheduler = 1.1.0**
https://pipelines.actions.githubusercontent.com/serviceHosts/205fed67-e757-4d4c-8ffc-a6fc67c1479e/_apis/pipelines/1/runs/1231/signedlogcontent/6?urlExpires=2022-07-08T11%3A49%3A02.4350750Z&urlSigningMethod=HMACV1&urlSignature=ACsbnK2UtZYfCph5VC6WX0v3csmJZ%2FH5%2FSPyJq9fGN4%3D

graph_scheduler 1.0.0 works fine, but both of these seem to force an earlier version of psyneulink to be installed (0.8.4.1), leading to issues further down the line on py3.9, involving eventually an early version of networkx

@kmantel Any reason why graph_scheduler would force psyneulink down?

**Comment by pgleeson** [comment]
@Ivy8127 I think this issue is at the root of som of your problems gettign the tests to pass.

**Comment by Ivy8127** [comment]
Alright. Py 3.9 MacOS seems to have a problem with installing grpcio and on Py 3.9 Ubuntu has import errors within the test_scheduler.py file. Is this related?

**Comment by kmantel** [comment]
I don't think this is related to graph-scheduler. graph-scheduler only requires psyneulink for a [dev install](https://github.com/kmantel/graph-scheduler/blob/main/dev_requirements.txt) which we don't use here (and even then, it requires a higher minimum version than 0.8.x.x).

**Comment by kmantel** [comment]
As mentioned in #239, I don't think the psyneulink lower bound should have been removed (it was previously ` psyneulink>=0.8.8.1`). The links posted are expired so I can't see what exactly the failures are from, but earlier versions of psyneulink are likely to cause failure for any psyneulink test examples we have.

**Comment by pgleeson** [comment]
Here: https://github.com/ModECI/MDF/runs/7471154506?check_suite_focus=true is some more information on the dependencies leading to the errors...

<img width="1112" alt="Screenshot 2022-07-22 at 16 35 42" src="https://user-images.githubusercontent.com/1556687/180474058-bb01b240-a9cf-49ad-a64f-4b66e64b5314.png">

@kmantel Why does pnl need an earlier version of modelspec?

**Comment by kmantel** [comment]
I think it's that between modelspec versions 0.1.5 and 0.2.1, the package changed API. Without restrictions in modeci_mdf, incompatible versions would be installed. This requirement will be bumped up with the next psyneulink release, but we could consider dropping this if in the future modeci_mdf and modelspec won't have breaking changes between them.

**Comment by pgleeson** [comment]
Great, that seems to fix it - I've tested the devel branch of pnl here: https://github.com/ModECI/MDF/runs/7501228717?check_suite_focus=true. Any idea when a new release is scheduled? 

Also there are a number of other upper bound pins in the requirements file. As we've removed this is MDF, is it soemthing you want to keep in PNL? 
cc @davidt0x

**Comment by kmantel** [comment]
Possibly this week; it's currently pending approval. But yes we would want to keep the upper bound in place. Any time a new release is up though, we can include it.

I also think the `graph-scheduler>=1.1.1` might be more strict than necessary - I think v1.0.0 would be all that's needed for basic functionality with the execution engine, and it seems that that is one of the parts of this dependency conflict.

**Comment by kmantel** [comment]
next psyneulink version has been released @pgleeson

**Comment by pgleeson** [comment]
Fixed for now, but some other issues with mdf/modelspec versions...
