### ISSUE TITLE
Move package to src/

### ISSUE THREAD

**Issue by davidt0x** [ModECI/MDF#31]
It is common to move the root of package to src/. That is `modeci_mdf` should be `src/modeci_mdf`. This helps make sure that testing is done against installed versions of the package always and not the local copy. [Here](https://scikit-hep.org/developer/packaging#package-structure-medium-priority) is a good description of why this is a good idea. As per convention, developers can install local editable installs with: 

```
pip install -e .[dev]
```

This ensures that modifications made to the local directory are reflected immediately in the installed package without having to reinstall. Without the `-e` argument, pip will copy the src to site-packages and `import modeci_mdf` will reference the site-packages copy, not your local copy. Developers should install with `-e`, users should install with simple pip install. The `[dev]` denotes that extra developer requirements (typically pytest at lease) should be installed.

If there are no objections then I will make this change in a standalone pull request.

**Comment by pgleeson** [comment]
This seems reasonable to me.
