### ISSUE TITLE
YAML importer incorrectly handles lists in value and function expressions

### ISSUE THREAD

**Issue by SamKG** [ModECI/MDF#314]
Currently, a property such as this:
```
value: [x,y]
```
will be imported as a python list ["x","y"].
This is likely not intended - expressions should only be stringtypes.

**Comment by pgleeson** [comment]
@SamKG I don't think any of the standard examples use that form. Can you add a (failing) test in a branch with an example of usage?

**Comment by pgleeson** [comment]
Closing for now, until there is a concrete example showing the error
