### ISSUE TITLE
Support PyTorch + Windows on py3.10.

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#316]
Currently failing, see here where it's disabled:
https://github.com/ModECI/MDF/blob/ac2642949cb6eea728de2f5e42b2595d7d82a6ae/.github/workflows/ci.yml#L75

but this combo will be common for potential users of MDF

**Comment by pgleeson** [comment]
To contribute to this, make a fork of the development branch: https://github.com/ModECI/MDF/tree/development, remove the line(s) in https://github.com/ModECI/MDF/blob/development/.github/workflows/ci.yml which disable testing on py10, and investigate the errors.

**Comment by davidt0x** [comment]
Yeah, that is weird. Looks like the problem is that scipy was built against a different numpy version than we are using. Let me see if I can reproduce locally.

**Comment by davidt0x** [comment]
This is caused by PsyNeuLink's pin on numpy I think. Installing PNL causes numpy to be downgraded after scipy is already installed, breaking it. I think the fix is either pin scipy maybe or get rid of the pin on numpy in psyneulink. 

@kmantel or @jvesely, can you remind me why we have this pin in PNL?

**Comment by jvesely** [comment]
> This is caused by PsyNeuLink's pin on numpy I think. Installing PNL causes numpy to be downgraded after scipy is already installed, breaking it. I think the fix is either pin scipy maybe or get rid of the pin on numpy in psyneulink.
> 
> @kmantel or @jvesely, can you remind me why we have this pin in PNL?

I don't see any failure reported. I can't tell if it's caused by the restriction on numpy. That is unlikely unless your target machine builds scipy from source.
The pin is there because newer numpy versions (>=1.22) return different numeric results.

**Comment by davidt0x** [comment]
hey @jvesely, here is the failure:

https://github.com/ModECI/MDF/actions/runs/3218592624/jobs/5262953193#step:11:74

See https://github.com/scipy/scipy/issues/16744 which has the scipy devs saying this can result with using the wrong numpy.

We are not building scipy but I think the issue might be that we install dependencies in two stages for MDF. The first stage is the core dependencies (this includes a package that depends on scipy). Numpy 1.23 is installed here as well. We then run core tests for the package. After that, we install the full MDF optional dependencies and this includes PsyNeuLink which causes numpy to get downgraded. I am not sure but I imagine if we install everything at once this might cause scipy to be appropriately installed. If this is the issue, maybe it is best we create another workflow for the full package with all optional dependencies test.

**Comment by kmantel** [comment]
Maybe it would make sense to test core and optional dependencies in separate jobs? With one install per job, pip's dependency resolver should handle any conflicts like this.

**Comment by davidt0x** [comment]
Yeah, that is what I was thinking.

**Comment by jvesely** [comment]
> hey @jvesely, here is the failure:
> 
> https://github.com/ModECI/MDF/actions/runs/3218592624/jobs/5262953193#step:11:74
> 
> See [scipy/scipy#16744](https://github.com/scipy/scipy/issues/16744) which has the scipy devs saying this can result with using the wrong numpy.
> 
> We are not building scipy but I think the issue might be that we install dependencies in two stages for MDF. The first stage is the core dependencies (this includes a package that depends on scipy). Numpy 1.23 is installed here as well. We then run core tests for the package. After that, we install the full MDF optional dependencies and this includes PsyNeuLink which causes numpy to get downgraded. I am not sure but I imagine if we install everything at once this might cause scipy to be appropriately installed. If this is the issue, maybe it is best we create another workflow for the full package with all optional dependencies test.

Right, the relevant error is:
```
 C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
```
Which specifically refers to numpy ABI version.

Installing dependencies in multiple steps is always risky. pip will handle incompatible package versions, but it won't touch packages that don't don't need version change. Not sure what tricks scipy is using in their install process.
I thought wheels were not supposed to depend on binary libraries outside of a restricted set, but that might only apply to manylinux.

Adding `--force-reinstall` should work around this issue.

**Comment by AniketARS** [comment]
Hey @pgleeson , I want to work on this issue as I've completed both the task suggested of Outreachy :), after this i will try to solve other issues

**Comment by jnsereko** [comment]
hello @pgleeson, can i kindly work on this?

**Comment by pgleeson** [comment]
I'm not sure if this is still an issue @jnsereko... Can you fork the repo, enable github actions on your fork, change the line above to check if the tests successfully run on pytorch + win + py3.10.

**Comment by pgleeson** [comment]
@mqnifestkelvin Have a look at this issue too, there might be relevant info here on getting the latest pytorch running with windows (or at least why tests might fail).

**Comment by mqnifestkelvin** [comment]
Okay @pgleeson, Thank you.

**Comment by peeplika** [comment]
is this still a issue??If its still not resolved I am willing to work on this.

**Comment by baimamboukar** [comment]
Hello @pgleeson, I would like to work on this please.

**Comment by pgleeson** [comment]
Sorry for leaving this open, PyTorch is now working fine on multiple versions of python on Windows.
