### ISSUE TITLE
Building docs fails on Readthedocs 

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#319]
See https://readthedocs.org/projects/mdf/builds/. Latest commit to master includes the restructured dependencies which may be the source of the issue (possibly this change: https://github.com/ModECI/MDF/commit/f41a4a30ab316ce2099967cdc96f73bbf9044c85#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L14?)

Could you look into this @parikshit14? Could also be to do with an update to sphinx or other libraries being used on Readthedocs to build... 

@davidt0x Could you give `pgleeson` permission on the https://readthedocs.org/projects/mdf? Can tweak it to test building the development branch too.

**Comment by parikshit14** [comment]
just checked the requirements.txt 
https://github.com/ModECI/MDF/blob/a4e0e6e65d0d377d941576748de20b3bb00d8e5d/docs/sphinx/requirements.txt#L2
i think it should have **all** or **optional** instead of **docs**

**Comment by pgleeson** [comment]
Worked nicely! Thanks @parikshit14
