### ISSUE TITLE
Black formatting

### ISSUE THREAD

**Issue by davidt0x** [ModECI/MDF#32]
We can setup black formatting as precommit hook. This can be configured to format code automatically. 

[Black Code Style](https://github.com/psf/black/blob/master/docs/the_black_code_style.md)

@pgleeson, I know you had some issues with this being automated. Could you take a look and tell me whether this sounds acceptable? If not, we can use flake8 (pycodestyle) but then people will have to fix the flake8 formatting issues manually.

**Comment by pgleeson** [comment]
As mentioned I'll run black on my local code and if all looks good this (auto formatting) can be enabled by default...

**Comment by pgleeson** [comment]
@davidt0x Have applied his in #43. All looks good, so feel free to add the precommit hook/auto formatting.

**Comment by davidt0x** [comment]
This should be in main now.
