### ISSUE TITLE
Add CONTRIBUTORS (or AUTHORS) document

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#326]
A markdown file at top level which can also be integrated into the sphinx based documentation. 

@sanjayankur31 any idea what the preferred convention/naming for this is?

**Comment by pgleeson** [comment]
Will be worked on in https://github.com/ModECI/MDF/tree/add_contributors.

Idea for the page: https://docs.neuroml.org/NeuroMLOrg/Contributors.html

Generated by: https://github.com/NeuroML/Documentation/blob/master/scripts/contributors/get_contributors.py

**Comment by Monsurat-Onabajo** [comment]
Noted

**Comment by Monsurat-Onabajo** [comment]
Hello, i have worked on the code scraping contributors, i noticed that in the idea for the page, their are some external resources linked to the page e.g the neuroML Organizational board, i want to ask if you want any external resources to also be linked to the page or if i should continue with uploading the page

**Comment by pgleeson** [comment]
@Monsurat-Onabajo happy for it to be kept simple initially, we can gradually improve it over time. First step is to get a helper script in place which will pull the contributors list from the GitHub API (as in the neuroml script above) and put it in a markdown file.

**Comment by Monsurat-Onabajo** [comment]
Hello, 
I am done with the codes for the contributors stage but i am having issues pushing it to the branch you specified, i kept on getting 
Remote: "permission to to ModECI/MDF.git denied to Monsurat-Onabajo
Fatal: unable to access 'https://github.com/ModECI/MDF.git/': The requested URL returned error:403
I have tried different ways to work around it but i am still stuck. 
![IMG_20221208_203806](https://user-images.githubusercontent.com/102332122/206552138-a68a4770-f30a-4e07-a317-23a10a00747e.jpg)

**Comment by pgleeson** [comment]
@Monsurat-Onabajo I've given you permission to write to the branch, so do a git pull and try again.
