### ISSUE TITLE
Fix broken links in examples on readthedocs

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#356]
Example pages are generated from MDF example markdown on GitHub, e.g. https://github.com/ModECI/MDF/blob/main/examples/MDF/README.md
Then generated on Readthedocs: e.g. https://mdf.readthedocs.io/en/latest/api/export_format/MDF/MDF.html

But the links are broken on that page.

**Comment by kusanele** [comment]
@pgleeson i created a pull requested. Please kindly have a look and advise further

**Comment by pgleeson** [comment]
Use branch https://github.com/ModECI/MDF/tree/update_readme_links

**Comment by pgleeson** [comment]
@kusanele I'd advise just working on the links for a first pull request, we can discuss options with the images during our next meeting.

**Comment by pgleeson** [comment]
Fixed
