### ISSUE TITLE
Test with Python 3.11

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#362]

**Comment by pgleeson** [comment]
@Monsurat-Onabajo Can you have a look at this when you get a chance? The easiest way would be to modify https://github.com/ModECI/MDF/blob/main/.github/workflows/ci.yml in a branch and see what works and what fails.

**Comment by Monsurat-Onabajo** [comment]
Ok, i will

**Comment by Monsurat-Onabajo** [comment]
ModECI is not compatible with python3.11 yet because the onnxruntime library is only compatible with python >=3.7,<3.11. you can view it here https://github.com/ModECI/MDF/actions/runs/3837482772/jobs/6532840055

**Comment by sanjayankur31** [comment]
onnxruntime and onnx both support py3.11 now.

Requires a new release of psyneulink---it supports py3.11 now too:  https://github.com/PrincetonUniversity/PsyNeuLink/pull/2694

Requires bumping of some deps to support their py3.11 versions. 

All deps pass in my testing, but lots of tests fail, mostly related to new versions of torch (2.0) and so on.

See #470 for a start

**Comment by pgleeson** [comment]
Development branch works nicely now with py3.11
