### ISSUE TITLE
Add an example of a model in Keras, and a script to generate an equivalent in MDF

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#385]
@kusanele This branch should be used for this work: https://github.com/ModECI/MDF/tree/test_keras. Switch to this branch and test it with your local virtual envirionment. 

It contains your latest changes and I've updated the test to run the keras example after installation of tensorflow (see step "Test interface TensorFlow" at https://github.com/ModECI/MDF/actions/runs/3988726347/jobs/6840264123)

Next steps:
- update Example.py to train and execute a simple keras network (rename the file to soemthign more appropriate)
- create a convert_to_mdf.py which loads the trained keras model and creates an equivalent in MDF

**Comment by pgleeson** [comment]
@kusanele Can you add this method for making a graph of the structure of the original keras model to your code: https://machinelearningmastery.com/visualize-deep-learning-neural-network-model-keras/, and then commit the png and add it to the readme? This can be compared with the generated graph for the mdf.

**Comment by kusanele** [comment]
Working on it

**Comment by pgleeson** [comment]
Latest version of this is in branch https://github.com/ModECI/MDF/tree/keras_interface/examples/TensorFlow/Keras/Keras_MDF

**Comment by pgleeson** [comment]
Merged to main: https://github.com/ModECI/MDF/tree/main/examples/TensorFlow/Keras
