### ISSUE TITLE
Remove sphinx pin to 3.x?

### ISSUE THREAD

**Issue by sanjayankur31** [ModECI/MDF#413]
Reported by @onoyiza here:

https://github.com/ModECI/MDF/discussions/398#discussioncomment-5255511

Sphinx 3.x does not work on py 3.10+

https://github.com/sphinx-doc/sphinx/issues/9816

but we pin to 3.x:

https://github.com/ModECI/MDF/blob/development/setup.py#L17

Worth investigating removing the pin at some point to latest versions of sphinx (4.x) can be used.

**Comment by pgleeson** [comment]
Fixed with https://github.com/ModECI/MDF/pull/466
