### ISSUE TITLE
Add stateful nodes

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#42]
Currently Nodes are stateless, they just calculate outputs and intermediate function values from the current inputs. There should be a way of assigning a variable inside a node as a **state** (can be a scalar, string or array), which can change over "time" as the graph is evaluated. 

Initial work on this here: https://github.com/ModECI/MDF/tree/states

The value of a state can change by:
1) specifying a **value** for the state, which depends on inputs, functions as well as the previous value of the state variable
2) when **an internal condition** is met (e.g. input above a certain value) the state is (discontinuously) changed. External conditions might be supported, but for now, assume sufficient information is coming in via edges to the node to make the decision. 
3) specifying a **TimeDerivative** on the node which specified how a state changes with time ([example in LEMS](https://github.com/ModECI/MDFTests/blob/main/NeuroML/FN_Definitions.xml#L49))

Obviously this is related to other open issues such as https://github.com/ModECI/MDF/issues/30

**Comment by jdcpni** [comment]
This sounds good to me.  Dave?  I think this should help with the LCA/DDM stuff, right?  Note that we needn’t, for now, associate state with a context, so it won’t be as powerful as the PNL implementation, but it will be much simpler and should do for now.


jdc



On Apr 19, 2021, at 12:22 PM, Padraig Gleeson ***@***.******@***.***>> wrote:



Currently Nodes are stateless, they just calculate outputs and intermediate function values from the current inputs. There should be a way of assigning a variable inside a node as a state (can be a scalar, string or array), which can change over "time" as the graph is evaluated.

Initial work on this here: https://github.com/ModECI/MDF/tree/states

The value of a state can change by:

  1.  specifying a value for the state, which depends on inputs, functions as well as the previous value of the state variable
  2.  when an internal condition is met (e.g. input above a certain value) the state is (discontinuously) changed. External conditions might be supported, but for now, assume sufficient information is coming in via edges to the node to make the decision.
  3.  specifying a TimeDerivative on the node which specified how a state changes with time (example in LEMS<https://github.com/ModECI/MDFTests/blob/main/NeuroML/FN_Definitions.xml#L49>)

Obviously this is related to other open issues such as #30<https://github.com/ModECI/MDF/issues/30>

**Comment by pgleeson** [comment]
Have an initial version of this in the states branch with options 1 and 3 above working with the simple scheduler, see https://github.com/ModECI/MDF/blob/states/examples/states.py#L57. Many things can potentially be updated about graph initialisation/incrementing nodes. Should be a good first basis for LCA/drift diffusion as you say though.

![state_example gv](https://user-images.githubusercontent.com/1556687/115444540-99e28a80-a20c-11eb-8e35-3b0cb9a3d21a.png)

**Comment by pgleeson** [comment]
Merged to main & getting tested so closing
