### ISSUE TITLE
simple_pytorch_to_mdf.py breaking in pytorch 2.0

### ISSUE THREAD

**Issue by mqnifestkelvin** [ModECI/MDF#469]
Hello, so on trying to integrate pytorch to mdf to sport the new pytorch features, I encountered the following errors running the script [simple_pytorch_to_mdf.py](https://github.com/ModECI/MDF/blob/1901625c8b360cbb468428a711965223959c4bcf/examples/PyTorch/simple_pytorch_to_mdf.py#L12) without any modification just on a different pytorch version, specifically pytorch 2.0.1. Immediately after running it I was greeted with the following errors:
```
Evaluated the graph in PyTorch, output: tensor([[-0.1304,  0.1030]], grad_fn=<AddmmBackward0>)(Tensor)
C:\Users\Mannie\Desktop\contribution\py39\lib\site-packages\modeci_mdf\interfaces\pytorch\importer.py:529: FutureWarning: 'torch.onnx.symbolic_helper._set_opset_version' is deprecated in version 
1.13 and will be removed in 2.0. Please remove its usage and avoid setting internal variables directly.
  _set_opset_version(modeci_onnx_opset_version)
C:\Users\Mannie\Desktop\contribution\py39\lib\site-packages\modeci_mdf\interfaces\pytorch\importer.py:538: FutureWarning: 'torch.onnx.symbolic_helper._set_opset_version' is deprecated in version 
1.13 and will be removed in 2.0. Please remove its usage and avoid setting internal variables directly.
  _set_opset_version(previous_opset_version)
Traceback (most recent call last):
  File "C:\Users\Mannie\Desktop\contribution\Modeci task\Pytorch_test\simple_py_torch_to_mdf.py", line 128, in <module>
    main()
  File "C:\Users\Mannie\Desktop\contribution\Modeci task\Pytorch_test\simple_py_torch_to_mdf.py", line 50, in main
    mdf_model, params_dict = pytorch_to_mdf(
  File "C:\Users\Mannie\Desktop\contribution\py39\lib\site-packages\modeci_mdf\interfaces\pytorch\importer.py", line 548, in pytorch_to_mdf
    consts = get_graph_constants(graph)
  File "C:\Users\Mannie\Desktop\contribution\py39\lib\site-packages\modeci_mdf\interfaces\pytorch\importer.py", line 193, in get_graph_constants
    consts[list(n.outputs())[0].unique()] = n["value"].numpy()
TypeError: 'torch._C.Node' object is not subscriptable
```
I was able to find this and am currently working on a work round [_set_opset_version(modeci_onnx_opset_version)](https://github.com/pytorch/pytorch/blob/main/torch/onnx/symbolic_helper.py#L1716) for the depreciated error by referring to the pytorch repository and making slight changes to the [importer.py](https://github.com/ModECI/MDF/blob/main/src/modeci_mdf/interfaces/pytorch/importer.py)
[526](https://github.com/ModECI/MDF/blob/4273a98fabae392e32e425b188c0f1ed88149f34/src/modeci_mdf/interfaces/pytorch/importer.py#L526C5-L526C23) 
[535](https://github.com/ModECI/MDF/blob/4273a98fabae392e32e425b188c0f1ed88149f34/src/modeci_mdf/interfaces/pytorch/importer.py#L535C4-L535C4) 

I am also getting this error which stems from [get_graph_constants](https://github.com/ModECI/MDF/blob/4273a98fabae392e32e425b188c0f1ed88149f34/src/modeci_mdf/interfaces/pytorch/importer.py#L173). 

Note: On running this script on pytorch version 1.11.0 I do not experience any such error instead the following output is displayed
```
Evaluated the graph in PyTorch, output: tensor([[-0
C:\Users\Mannie\Desktop\contribution\py310\lib\sitelue in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order t

Init graph: SimpleNetGraph
Evaluating graph: SimpleNetGraph, root nodes: ['Res
Evaluated the graph in PyTorch, output: [[-0.130407
Passed all comparison tests!
graph(%0 : Float(1, 3, 224, 224, strides=[150528, 5
      %fc1.weight : Float(240, 150528, strides=[150
      %fc1.bias : Float(240, strides=[1], requires_
      %fc2.weight : Float(120, 240, strides=[240, 1
      %fc2.bias : Float(120, strides=[1], requires_
      %fc3.weight : Float(50, 120, strides=[120, 1]
      %fc3.bias : Float(50, strides=[1], requires_g
      %fc4.weight : Float(2, 50, strides=[50, 1], r
      %fc4.bias : Float(2, strides=[1], requires_gr
  %9 : Long(2, strides=[1], device=cpu) = onnx::Conh_test\simple_py_torch_to_mdf_with_only_torchfx.py:
  %10 : Float(1, 150528, strides=[150528, 1], requitest\simple_py_torch_to_mdf_with_only_torchfx.py:22
  %11 : Float(1, 240, strides=[240, 1], requires_grDesktop\contribution\py310\lib\site-packages\torch\
  %12 : Float(1, 240, strides=[240, 1], requires_gr\functional.py:1438:0
  %13 : Float(1, 120, strides=[120, 1], requires_grDesktop\contribution\py310\lib\site-packages\torch\
  %14 : Float(1, 120, strides=[120, 1], requires_gr\functional.py:1438:0
  %15 : Float(1, 50, strides=[50, 1], requires_gradsktop\contribution\py310\lib\site-packages\torch\nn
  %16 : Float(1, 50, strides=[50, 1], requires_gradunctional.py:1438:0
  %17 : Float(1, 2, strides=[2, 1], requires_grad=1top\contribution\py310\lib\site-packages\torch\nn\m
  return (%17)
```

**Comment by parikshit14** [comment]
I think there is a difference in how 
https://github.com/ModECI/MDF/blob/22dcf9cfb18b9ec4638063cd48212e7c8603a61a/src/modeci_mdf/interfaces/pytorch/importer.py#L527
returns the graph, because even if you pass a torchscript IR or torch.fx IR is doesn't discriminate between them but rather what it return for torch 2.0 vs for torch 1.11.

One of the options currently is string parsing like the ones present in importer but don't know if we can generalize it enough or if there is a better way to extract the attributes.
