### ISSUE TITLE
Refactor PyTorch_MDF examples to ease benchmarking

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#475]
@mqnifestkelvin, as discussed, the python examples in here: https://github.com/ModECI/MDF/tree/main/examples/PyTorch/PyTorch_MDF could be refactored to add 2 methods:

```
get_pytorch_model() # returns the pytorch model created or loaded
get_example_input() # returns an example input tensor of correct size - should be random valued
```
which should be used in the main methods of the py files themselves for testing the models (note: a comparison of the output for each example pytorch vs MDF should be added and fail if different).

These methods can then be called in a new script for benchmarking, where each model is loaded in turn, ~10 tests runs done in each of pytorch/mdf, and a comparison of speed in each performed.

**Comment by mqnifestkelvin** [comment]
Hello mentor @pgleeson I have started looking into this and will give a feed back as soon as I am done. With the first demonstration.

**Comment by pgleeson** [comment]
Implemented in https://github.com/ModECI/MDF/pull/487
