### ISSUE TITLE
Support latest graph_scheduler

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#496]
Current version only works with graph_scheduler<1.2.0, e.g. see failing tests at:

https://github.com/ModECI/MDF/actions/runs/7739807955

Any idea what's changed in the latest graph_scheduler @kmantel?

**Comment by kmantel** [comment]
There's a new check for invalid termination condition input, and the two failing tests look to be hitting that. It looks like they don't specify a time scale for the termination condition:
https://github.com/ModECI/MDF/blob/2e9cd9c41aed8486b93ba7c0ac06258a0bfb20a1/examples/ACT-R/count.json#L413-L422


A correct example:
https://github.com/ModECI/MDF/blob/2e9cd9c41aed8486b93ba7c0ac06258a0bfb20a1/examples/PsyNeuLink/SimpleFN.json#L15-L27


In prior graph-scheduler versions, that condition would have been silently ignored. 

This line looks like the culprit: https://github.com/ModECI/MDF/blob/2e9cd9c41aed8486b93ba7c0ac06258a0bfb20a1/src/modeci_mdf/interfaces/actr/importer.py#L231

**Comment by pgleeson** [comment]
@davidt0x Did you suggest in our last call that your latest PR solved this issue?

**Comment by davidt0x** [comment]
I did suggest that but I forgot to include the fix, will generate another PR, sorry for the confusion.

**Comment by davidt0x** [comment]
This issue is fixed with PR #524
