### ISSUE TITLE
Tasks/ Milestones

### ISSUE THREAD

**Issue by ChisomNwankwo** [ModECI/MDF#513]
Task 1: Read the MDF paper, install MDF locally and try some of the example models

The paper introducing MDF can be found at https://mdf.readthedocs.io/en/latest/api/MDFpaper.html. Have a read over it, don’t worry if you don’t understand it all (it’s mainly intended for neuroscientists) but it should give you a feel for the aims of the project. See https://mdf.readthedocs.io/en/latest/api/Installation.html for installation details for the MDF package. Run the example Python scripts in https://github.com/ModECI/MDF/tree/main/examples/MDF to get a feel for the language.

Task 2: Create an OSB account and edit a Jupyter notebook to create a novel MDF model

Create a new account on Open Source Brain v2:[ https://www.v2.opensourcebrain.org](https://www.v2.opensourcebrain.org/)
Create a new[ workspace](https://docs.opensourcebrain.org/OSBv2/Workspaces.html) from the[ ModECI MDF OSBv2 repository](https://www.v2.opensourcebrain.org/repositories/1) (which points to the main MDF GitHub repository here:[ https://github.com/ModECI/MDF](https://github.com/ModECI/MDF))
Open the workspace in the[ JupyterLab application](https://docs.opensourcebrain.org/OSBv2/JupyterLab.html).
Install the latest version of MDF which has been copied into the workspace (launch a Terminal, go to /opt/workspace/ModECI MDF/main, type pip install .)
Open the simple example Jupyter notebook (at /opt/workspace/ModECI MDF/main/examples/SimpleExample.ipynb) and go through this to understand the main concepts in MDF.
Create a new notebook in your workspace which creates an MDF model with a number of connected nodes, with a unique mathematical expression in each and at least one time derivative ([example](https://github.com/ModECI/MDF/blob/main/examples/MDF/States.yaml#L16)). It should represent a simple model of a dynamical system in biology or physics containing an ordinary differential equation, and demonstrate your understanding of MDF.
Email us a link to the workspace (see Outreachy for mentors' contact details).
To get a feel for what OSBv2 can be used for see the[ Guided tour of OSBv2](https://docs.opensourcebrain.org/OSBv2/Guided_tour.html)

Task 3: Create a simple Streamlit application which uses MDF

A simple graphical application should be created using Streamlit which imports MDF and allows a model to be executed at the press of a button, with output displayed. Ideally it would use the example MDF you have created above, and potentially plots the output at multiple time points (as in this [example](https://github.com/ModECI/MDF/tree/main/examples/MDF/RNN#integrate-and-fire-iaf-neuron-model)). Email us a link to where the public app is hosted (e.g. a Space on HuggingFace).

**Comment by pgleeson** [comment]
@ChisomNwankwo It would be better to record your tasks/progress in issues in your own fork of this repo. This issue list is for changes required to/questions about the current codebase. You can also use the Discussions forum for general queries.
