### ISSUE TITLE
Missing Link to Functions List in Parameter Section in Documentation

### ISSUE THREAD

**Issue by rimjhimittal** [ModECI/MDF#515]
In the Parameters section of documentation [here](https://mdf.readthedocs.io/en/latest/api/Specification.html#parameter) , in the allowed parameters table-> function field, the link to built-in MDF Functions is missing
<img width="751" alt="image" src="https://github.com/ModECI/MDF/assets/100460360/077841bc-6aa2-4f71-9cbf-612d872235f8">

**Comment by rimjhimittal** [comment]
do we have to use the [same link as in Function section](https://mdf.readthedocs.io/en/latest/api/MDF_function_specifications.html) here?

**Comment by pgleeson** [comment]
To fix, properly indent this:
https://github.com/ModECI/MDF/blob/067ff411eb04f8cb6771f631ea1cd86aafa24b49/src/modeci_mdf/mdf.py#L165-L166
like this:
https://github.com/ModECI/MDF/blob/067ff411eb04f8cb6771f631ea1cd86aafa24b49/src/modeci_mdf/mdf.py#L67-L68

**Comment by rimjhimittal** [comment]
Thank you for the clarification. I closed the issue because I believed it had been addressed. 
 Looking forward to seeing the updates in action after the release! 🚀
