### ISSUE TITLE
pypi refusing to make new release as modeci requires verified email

### ISSUE THREAD

**Issue by pgleeson** [ModECI/MDF#531]
See https://github.com/ModECI/MDF/actions/runs/8882790702/job/24388216034

@davidt0x I believe you have access to this. Could you verify an email for yourself there, or add https://pypi.org/user/pgleeson/ as a manager? Thanks!

**Comment by davidt0x** [comment]
Hey, ok, I have verified my email and enable 2FA for the modeci user. I have also made you an Owner on the modeci project. You were set to maintainer for some reason. I think the issue should be resolved now though.,

**Comment by pgleeson** [comment]
Thanks @davidt0x. Released on pypi now.
