### ISSUE TITLE
Required (and optional) dicts not appearing in json/yaml

### ISSUE THREAD

**Issue by kmantel** [ModECI/MDF#57]
A basic example in of 
```mod_graph0 = Graph(id="Test")```

produces the json

```
{
    "Test": {}
}
```

and yaml

```
Test: {}
```

which are missing entries `"nodes": {}` and `"edges": {}` . These are listed as required in the README spec. `"parameters": {}` and `"conditions": {}` are also missing, but these are listed as optional. Similarly, `parameters` is missing from `Node` if unspecified, although this isn't explicitly mentioned in the spec as required or not.

We should either update the `to_json` and `to_yaml` methods for `Graph` (or the underlying neuromllite classes) to always generate `nodes` and `edges` entries,  or update these in the spec as optional. If we do the former, I think we should also consider including empty entries for `parameters` and `conditions` as well.

**Comment by pgleeson** [comment]
This is the intended behaviour and for maximum flexibility and producing what the programmer probably wants to happen, should be left as such.

However, there is certainly a need for a quick way to get a "best practice" MDF model with all required parts filled in. This can be:
- a helper method on Model `create_new_mdf_model(model_id, graph_id)` which returns a Model with all required elements and possibly some default placeholders added
- an optional attribute on `to_json` etc.: `fill_missing_required_elements`

That said, it should be assumed by any reader/parser that a missing edges or `"edges": {}` both imply: there are no edges... A graph is a graph and by definition it can have some edges, if a serialised graph doesn't say anything about edges, it is still a graph, but with no edges.

**Comment by kmantel** [comment]
I understand, so this is basically the second case I mentioned. If none of the fields are required, the description should be updated to reflect that and ideally explicitly mentioned that all fields are optional. Otherwise it can be confusing for parsing when a "required" field is not present.
