### ISSUE TITLE
JSON vs. YAML

### ISSUE THREAD

**Issue by jeremyrl7** [ModECI/MDF#6]
Decide whether to use JSON or YAML for MDF files.

**Comment by pgleeson** [comment]
Hopefully we won't have to choose, and support both. Using the NeuroMLlite library for building the specification, it shoud be possible to implement to_yaml() and load_from_yaml() in the same way as json is supported:
https://github.com/NeuroML/NeuroMLlite/blob/master/neuromllite/BaseTypes.py#L122

That core feature for specifying a data model in python (e.g. here: https://github.com/ModECI/MDF/blob/main/MDF.py#L45) and allowing easy serialisation can be pulled out into a separate python pacakage MDF and NMLlite can share eventually.

**Comment by jdcpni** [comment]
Yep, nice.


jdc



On Dec 17, 2020, at 2:18 PM, Padraig Gleeson <notifications@github.com<mailto:notifications@github.com>> wrote:



Hopefully we won't have to choose, and support both. Using the NeuroMLlite library for building the specification, it shoud be possible to implement to_yaml() and load_from_yaml() in the same way as json is supported:
https://github.com/NeuroML/NeuroMLlite/blob/master/neuromllite/BaseTypes.py#L122

That core feature for specifying a data model in python (e.g. here: https://github.com/ModECI/MDF/blob/main/MDF.py#L45) and allowing easy serialisation can be pulled out into a separate python pacakage MDF and NMLlite can share eventually.

**Comment by pgleeson** [comment]
Example of MDF in YAML format can be found here: https://github.com/ModECI/MDF/blob/development/examples/ABCD.yaml and here; https://github.com/ModECI/MDF/blob/development/examples/Simple.yaml

This branch of the MDF repo requires an updated version of NeuroMLlite in here: https://github.com/NeuroML/NeuroMLlite/tree/update_format, which can read and write models as JSON or YAML.

**Comment by pgleeson** [comment]
YAML support added in #15
