### ISSUE TITLE
MDF scheduling wrappers

### ISSUE THREAD

**Issue by kmantel** [ModECI/MDF#61]
>One thing that would be nice though is if there was a wrapper class around the PNL specific classes/fields so that all the terms used (trial/timescale/sequence) are MDF's own and can be changed/updated easily on our side without impacting PNL. Also the "innards" of that wrapper class can eventually substituted with a MDF specific implentation (or a standalone schedluer) without too much additional changes...

>Thinking a bit more about this I feel this file (modeci_mdf/scheduler.py) is the proper place for the "wrapper" class/fields (i.e. the MDFScheduler) which hides the specifics of PNI in an MDF specific API, and the EvaluableGraph could be extracted out & just use that API...

_Originally posted by @pgleeson in https://github.com/ModECI/MDF/issues/60#issuecomment-832594701_, https://github.com/ModECI/MDF/pull/60#issuecomment-832893942

**Comment by kmantel** [comment]
The way I see it, there isn't much to wrap. The scheduler is ok with just accepting the ids of MDF nodes, and EvaluableGraph handles the interface between MDF and the scheduler. As for naming of things like "trial", the MDF versions of these terms can be used via monkeypatching in 4745e87. While custom naming for these time scales could be implemented in the future by the scheduler, the meaning of the scales is fixed and critical to the scheduler's function.

**Comment by pgleeson** [comment]
Out of date now I believe
