### ISSUE TITLE
Specify Node Connectivity using Ports or Edges

### ISSUE THREAD

**Issue by jeremyrl7** [ModECI/MDF#7]
Decide if a node's list of input/output ports and their names specifies the node's connections to other nodes, or if the list of edges specifies connectivity between nodes.

**Comment by pgleeson** [comment]
Ideally edges should be explicitly specified. Would be too easy for default ids to be set on an output port of a node (e.g. port0) and that gets accidentally connected to something with the same id for an input port.

**Comment by pgleeson** [comment]
I believe inferring connectivity between nodes due to input/output ports (no explicit edges) is out of the scope of the language at this stage. Can revisit if a relevant use case arises.
